//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userSkill
    {
        public int id { get; set; }
        public Nullable<int> id_skill { get; set; }
        public string id_user { get; set; }
        public Nullable<int> lvl { get; set; }
        public Nullable<decimal> xp { get; set; }
    
        public virtual skill skill { get; set; }
    }
}
