//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xp
    {
        public int id { get; set; }
        public Nullable<int> id_xpTable { get; set; }
        public Nullable<int> lvl { get; set; }
        public Nullable<int> xps { get; set; }
        public Nullable<int> dif { get; set; }
    
        public virtual xpTable xpTable { get; set; }
    }
}
